name: ci-golang-workflow
on: [push]
jobs:
  check-application:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup-GO
        uses: actions/setup-go@v5
        with:
          go-version: '1.20'
      - run: go mod tidy
      - run: go test
      - run: go run soma.go
