name: ci-golang-workflow
on:
  pull_request:
    branches:
      - develop
jobs:
  build:
    strategy:
      matrix:
        go: ['1.14','1.15','1.19']
    name: Verificando_Aplicacao
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup-GO
        uses: actions/setup-go@v5
        with:
          go-version: ${{matrix.go}}
      - run: go test
      - run: go run soma.go
