name: ci-golang-workflow
on:
  pull_request:
    branches:
      - develop


      
jobs:
  check-application:
    name: Verificando_Aplicacao
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup-GO
        uses: actions/setup-go@v5
        with:
          go-version: '1.20'
      - run: go test
      - run: go run soma.go
